package org.joel.kimwanyisacco.model.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,

    MEMBER_REGISTERED,
    MEMBER_UPDATED,
    MEMBER_DEACTIVATED,

    DEPOSIT_PROCESSED,
    WITHDRAWAL_PROCESSED,

    LOAN_APPLIED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_REPAYMENT_RECORDED,

    INTERNAL_TRANSFER_COMPLETED,
    INTERNAL_TRANSFER_FAILED,

    PASSWORD_CHANGED
}